---
title: "git_01"
author: "Isabela Bercian"
date: "Spring 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

A boat beneath a sunny sky,  
 Lingering onward dreamily  
 In an evening of July —  
 Children three that nestle near,  
 Eager eye and willing ear,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

We were running out of breath, as we ran out to meet ourselves. We  
 were surfacing the edge of our ancestors’ fights, and ready to strike.  
 It was difficult to lose days in the Indian bar if you were straight.  
 Easy if you played pool and drank to remember to forget. We  
 made plans to be professional — and did. And some of us could sing  
 so we drummed a fire-lit pathway up to those starry stars. Sin  
 was invented by the Christians, as was the Devil, we sang. We  
 were the heathens, but needed to be saved from them — thin  
 chance. We knew we were all related in this story, a little gin  
 will clarify the dark and make us all feel like dancing. We  
 had something to do with the origins of blues and jazz  
 I argued with a Pueblo as I filled the jukebox with dimes in June,  
 forty years later and we still want justice. We are still America. We  
 know the rumors of our demise. We spit them out. They die  
 soon.  
